export const USER_SIGNUP_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNIN_GOOGLE_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_GOOGLE_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_GOOGLE_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT_REQUEST = 'USER_SIGNOUT_REQUEST';
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
export const USER_SIGNOUT_FAIL = 'USER_SIGNOUT_FAIL';

export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL';

export const RESET_ERROR = 'RESET_ERROR';
