export const CREATE_ITEM_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_ITEM_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_ITEM_FAIL = 'CREATE_PRODUCT_FAIL';

export const ITEM_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const ITEM_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const ITEM_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const UPDATE_ITEM_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_ITEM_FAIL = 'UPDATE_PRODUCT_FAIL';

export const DELETE_ITEM_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_PRODUCT_FAIL';

export const CHECK_ITEM_REQUEST = 'CHECK_ITEM_REQUEST';
export const CHECK_ITEM_SUCCESS = 'CHECK_ITEM_SUCCESS';
export const CHECK_ITEM_FAIL = 'CHECK_ITEM_FAIL';
